# Generated by Django 5.2.2 on 2025-06-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('public_ip', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
